SDLPATH 	=C:\mingw_dev
IncludePath =$(SDLPATH)\include\SDL2
LDPATH 		=$(SDLPATH)\lib
CFlags 		=-static -I $(IncludePath) -L $(LDPATH) -g
LDFlags		=-lmingw32 -lSDL2main -lSDL2.dll
ExeName 	=StarFighter.exe
Headers		=Game.hpp

$(ExeName): StarFighter.cpp $(Headers)
	g++ $(CFlags) -o $@ $< $(LDFlags)
	
clean:
	delete $(ExeName)
